version: "3.8"

services:
  mysql:
    container_name: mysql-altastore
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=final_project_acp12
      - MYSQL_PASSWORD=password
    networks:
      - altastore_network
  final-project-acp12:
    container_name: altastore
    image: final-project-acp12:1.0.0
    environment:
      - DB_HOST=0.0.0.0
      - DB_PORT=3307
      - DB_NAME=final_project_acp12
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - 8000:8000
    networks:
      - altastore_network
      
networks:
  altastore_network:
    name: altastore_network